# Site dev settings
title: Whose Data?
email:
description: >
    Whose Data? aims to make it easier for Canadians to answer key questions about who owns -- and what options we have to control -- data collected about us via common online and offline activities.
baseurl: ""
url: "http://127.0.0.1:8080"
twitter_username: whosedata
github_username:  samanthaburton

# Build settings
markdown: kramdown

include: ['_pages']
